### ISSUE TITLE
Disables Toolbar and Statusbar when the modal view is loading

### ISSUE THREAD

**Issue by aminya** [atom-community/atom-ide-hyperclick#100]
When the modal view shows up it hides Toolbar and Statusbar temporarily.
![hyperclick](https://user-images.githubusercontent.com/16418197/102124421-db51cc00-3e0d-11eb-946a-ae5cd4bf73c3.gif)

**Comment by UziTech** [comment]
Are you sure that is a bug from this package? I don't see anything in the code that would hide the status bar or toolbar.

**Comment by aminya** [comment]
I will approach this later. I had seen this issue when I used css containment on datatips in Atom core. The modal HTML goes out of the workspace and so it hides the toolbars for a second.

**Comment by UziTech** [comment]
@aminya is this still an issue?

**Comment by UziTech** [comment]
Going to close this as it doesn't seems to be an issue with this package.
